name: Auto Deploy to VPS

on:
  push:
    branches: [ "main" ]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /www/wwwroot/kerjapro.com/project-solutions/
            git pull origin main
            
            # Masak Frontend
            cd frontend
            npm install
            npm run build
            
            # Bersihkan public lama dan copy yang baru
            rm -rf ../backend/public/assets
            cp -r dist/* ../backend/public/
            
            # Beresin Backend
            cd ../backend
            composer install --no-dev
            php artisan migrate --force
            php artisan optimize:clear